export {default as Home} from './Home'
export {default as Artists} from './Artists'
export {default as Artist} from './Artist'
export {default as About} from './About'
export {default as NotFound} from './NotFound'
